In [13]:
import random
import numpy as np
import torch
from skimage import data
from skimage.transform import resize

im = data.coffee()
im = resize(im, (im.shape[0] // 8, im.shape[1] // 8), mode='reflect', preserve_range=True, anti_aliasing=True).astype(np.uint8)
im = np.swapaxes(np.swapaxes(im, 0, 2), 1, 2)
im = torch.from_numpy(im)

a = random.uniform(0,2)
b = random.uniform(-50,50)

In [14]:
im.shape

torch.Size([3, 50, 75])

In [15]:
a

0.5863599641795723

In [16]:
b

4.074135373341946

In [29]:
out = a * im.float() + b

In [30]:
out

tensor([[[ 16.3877,  16.9741,  19.9059,  ..., 131.9006, 133.0733, 134.2461],
         [ 15.8013,  17.5604,  21.0786,  ..., 135.4188, 134.8324, 130.7279],
         [ 16.9741,  18.7331,  22.2513,  ..., 136.0051, 133.0733, 129.5552],
         ...,
         [122.5189, 126.6234, 124.8643,  ..., 100.2372, 101.4099,  91.4418],
         [121.3461, 120.7598, 123.1052,  ...,  99.6508,  97.8917,  89.0963],
         [118.4143, 123.1052, 127.2097,  ..., 101.4099,  90.8554,  90.2691]],

        [[ 11.6968,  12.2832,  14.6286,  ..., 102.5826, 106.6871, 107.2735],
         [ 11.6968,  12.8695,  15.2150,  ..., 109.0326, 110.7916, 103.7553],
         [ 12.2832,  13.4559,  15.8013,  ..., 111.9644, 106.6871, 101.4099],
         ...,
         [ 88.5100,  95.5463,  93.7872,  ...,  50.9829,  50.9829,  44.5330],
         [ 87.3372,  87.3372,  90.8554,  ...,  50.3966,  48.0511,  41.6012],
         [ 85.5782,  91.4418,  96.7190,  ...,  52.1557,  42.7739,  43.9466]],

        [[  8.1787,   8.7650,   9.9377,  ...

In [31]:
out = torch.round(out)

In [32]:
torch.clamp(out, 0, 255)

tensor([[[ 16.,  17.,  20.,  ..., 132., 133., 134.],
         [ 16.,  18.,  21.,  ..., 135., 135., 131.],
         [ 17.,  19.,  22.,  ..., 136., 133., 130.],
         ...,
         [123., 127., 125.,  ..., 100., 101.,  91.],
         [121., 121., 123.,  ..., 100.,  98.,  89.],
         [118., 123., 127.,  ..., 101.,  91.,  90.]],

        [[ 12.,  12.,  15.,  ..., 103., 107., 107.],
         [ 12.,  13.,  15.,  ..., 109., 111., 104.],
         [ 12.,  13.,  16.,  ..., 112., 107., 101.],
         ...,
         [ 89.,  96.,  94.,  ...,  51.,  51.,  45.],
         [ 87.,  87.,  91.,  ...,  50.,  48.,  42.],
         [ 86.,  91.,  97.,  ...,  52.,  43.,  44.]],

        [[  8.,   9.,  10.,  ...,  77.,  82.,  81.],
         [  8.,   9.,  11.,  ...,  84.,  87.,  79.],
         [  9.,  10.,  11.,  ...,  88.,  83.,  77.],
         ...,
         [ 62.,  70.,  69.,  ...,  25.,  25.,  22.],
         [ 62.,  61.,  64.,  ...,  25.,  23.,  20.],
         [ 60.,  65.,  70.,  ...,  26.,  21.,  22.]]]

In [27]:
out = out.to(torch.uint8)

In [28]:
out

tensor([[[ 16,  17,  20,  ..., 132, 133, 134],
         [ 16,  18,  21,  ..., 135, 135, 131],
         [ 17,  19,  22,  ..., 136, 133, 130],
         ...,
         [123, 127, 125,  ..., 100, 101,  91],
         [121, 121, 123,  ..., 100,  98,  89],
         [118, 123, 127,  ..., 101,  91,  90]],

        [[ 12,  12,  15,  ..., 103, 107, 107],
         [ 12,  13,  15,  ..., 109, 111, 104],
         [ 12,  13,  16,  ..., 112, 107, 101],
         ...,
         [ 89,  96,  94,  ...,  51,  51,  45],
         [ 87,  87,  91,  ...,  50,  48,  42],
         [ 86,  91,  97,  ...,  52,  43,  44]],

        [[  8,   9,  10,  ...,  77,  82,  81],
         [  8,   9,  11,  ...,  84,  87,  79],
         [  9,  10,  11,  ...,  88,  83,  77],
         ...,
         [ 62,  70,  69,  ...,  25,  25,  22],
         [ 62,  61,  64,  ...,  25,  23,  20],
         [ 60,  65,  70,  ...,  26,  21,  22]]], dtype=torch.uint8)